# Generated by Django 4.1.6 on 2023-02-19 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editoriales', '0001_initial'),
        ('autores', '0001_initial'),
        ('generos', '0001_initial'),
        ('libros', '0002_alter_libro_autor_alter_libro_editorial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro_v4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('año_publicacion', models.IntegerField()),
                ('n_paginas', models.IntegerField()),
                ('idioma', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros_autor_v4', to='autores.autor')),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros_editorial_v4', to='editoriales.editorial')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros_genero', to='generos.genero')),
            ],
        ),
    ]
